language: node_js
sudo: false

os:
  - linux
  - osx

node_js:
  - '6.0'
  - '7'
  - '8'
  - 'node'

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test

after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
